### ISSUE TITLE
Typescript SMT throws when inserting just a zero value & then getting a proof

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#451]
**Describe the bug**
I'm not entirely sure if this is unexpected behavior but figured I'd note it down.

During my tests I noticed that when I tried to get a merkle proof from a tree where I just inserted 32 bytes of zeros I got the following error:

```
     Error: Assertion failed
      at assert (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/bn.js/lib/bn.js:6:21)
      at BN.iushrn (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/bn.js/lib/bn.js:2000:5)
      at BN.ishrn (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/bn.js/lib/bn.js:2059:17)
      at BN.shrn (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/bn.js/lib/bn.js:2073:25)
      at BigNumber.shiftRight (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/types/number.ts:301:35)
      at SparseMerkleTreeImpl.isLeft (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/app/block-production/merkle-tree.ts:553:8)
      at SparseMerkleTreeImpl.getChildSiblingHash (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/app/block-production/merkle-tree.ts:321:34)
      at treeLock.acquire (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/app/block-production/merkle-tree.ts:245:28)
      at /Users/karlfloersch/workspace/ethereum/pigi/node_modules/async-lock/lib/index.js:125:12
      at AsyncLock._promiseTry (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/async-lock/lib/index.js:249:31)
      at exec (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/async-lock/lib/index.js:124:9)
      at AsyncLock.acquire (/Users/karlfloersch/workspace/ethereum/pigi/node_modules/async-lock/lib/index.js:140:3)
      at SparseMerkleTreeImpl.getMerkleProof (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/app/block-production/merkle-tree.ts:233:26)
      at Context.it.only (test/merklization/RollupMerkleUtils.spec.ts:71:47)
```

I don't think we'll run into this in practice but figured I'd note it down in case it comes up later.

**Steps to reproduce**
1. Create some test file
2. Drop in the following test (assuming imports are handled)
```
    it.only('shouldnt throw now', async () => {
      async function createSMTfromDataBlocks(
        dataBlocks: Buffer[]
      ): Promise<SparseMerkleTreeImpl> {
        const treeHeight = Math.ceil(Math.log2(dataBlocks.length)) + 1
        log('Creating tree of height:', treeHeight)
        const theTree = getNewSMT(treeHeight)
        for (let i = 0; i < dataBlocks.length; i++) {
          await tree.update(new BigNumber(i, 10), dataBlocks[i])
        }
        return theTree
      }

      const bufBlock = [Buffer.from('00'.repeat(32))]
      const tree = await createSMTfromDataBlocks(bufBlock)
      const root = await tree.getRootHash()
      // This i think fails
      const inclusionProof = await tree.getMerkleProof(new BigNumber(0), bufBlock[0])
    })
```

**Expected behavior**

**Specifications**
 - Version:
 - OS:
 - Node Version: 11

**Comment by willmeister** [comment]
@karlfloersch, where is `createSMTfromDataBlocks(...)` defined? It looks like the height of the tree may be < 2 because the
```
      at SparseMerkleTreeImpl.isLeft (/Users/karlfloersch/workspace/ethereum/pigi/packages/core/src/app/block-production/merkle-tree.ts:553:8)

```
line is 
```
      [BigNumber].shiftRight(this.height - 2)
```

We may just need to guarantee that height is >= 2 in the constructor
